{
    'name': 'SMS Campaign Scheduler - automatic SMS campaigns with SMS Gateway',
    'version': '18.0.1.0.0',
    'category': 'Marketing/SMS Marketing',
    'summary': 'Automate recurring SMS campaigns - daily, weekly, or monthly with timezone-aware scheduling',
    'description': 'Schedule SMS campaigns that run automatically on a recurring basis. Pick a template, segment, frequency (daily / weekly / monthly) and timezone-aware send time. Each execution creates a real Odoo mass mailing campaign with full delivery tracking. Requires SMS Gateway module.',
    'author': 'Michal Varys',
    'website': 'https://michalvarys.eu',
    'support': 'info@michalvarys.eu',
    'license': 'LGPL-3',
    'price': 49.00,
    'currency': 'EUR',
    'depends': [
        'sms_gateway',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron_data.xml',
        'views/campaign_schedule_views.xml',
        'views/menu_views.xml',
    ],
    'images': ['static/description/cover.png'],
    'installable': True,
    'application': False,
    'auto_install': False,
}
