{
    'name': 'SMS Gateway - Replace Odoo IAP and Send SMS via Android Phone',
    'version': '18.0.2.6.0',
    'category': 'Marketing/SMS Marketing',
    'summary': 'Replace Odoo IAP SMS with your own Android phone - zero per-message cost, load balancing, mass mailing integration',
    'description': 'Use your physical Android phone as an SMS gateway for Odoo 18. Register multiple phones with QR pairing, send bulk SMS campaigns through Odoo Mass Mailing, set daily and monthly limits, auto-assign messages with load balancing, and track delivery status in real time. No IAP credits needed - every SMS is sent from your own SIM card.',
    'author': 'Michal Varys',
    'website': 'https://michalvarys.eu',
    'support': 'info@michalvarys.eu',
    'license': 'LGPL-3',
    'price': 99.00,
    'currency': 'EUR',
    'depends': ['base_setup', 'sms', 'mass_mailing_sms', 'phone_validation', 'sale', 'point_of_sale'],
    'external_dependencies': {'python': ['qrcode']},
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron_data.xml',
        'data/sms_marketing_segment_data.xml',
        'views/sms_gateway_phone_views.xml',
        'views/mailing_mailing_views.xml',
        'views/res_config_settings_views.xml',
        'views/sms_sms_views.xml',
        'views/sms_gateway_send_wizard_views.xml',
        'views/sms_marketing_template_views.xml',
        'views/sms_campaign_wizard_views.xml',
        'views/res_partner_views.xml',
    ],
    'images': ['static/description/cover.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
}
