from . import mailing_trace
from . import sms_gateway_phone
from . import sms_sms
from . import mailing_mailing
from . import res_config_settings
from . import sms_gateway_inbound
from . import sms_marketing_segment
from . import sms_marketing_template
from . import res_partner_stats
from . import res_partner
from . import sms_gateway_release
